import React, { Component } from "react";
import kendinonar from "../images/kendinonar.png";
import myblog from "../images/myblog.png";
import sorular from "../images/sorular.png";
import floppyhome from "../images/floppyhome.png";
import kendinonarmobile from "../images/kendinonarmobile.png";
import myblogmobile from "../images/myblogmobile.png";
import sorularmobile from "../images/sorularmobile.png";
import floppyhomemobile from "../images/floppyhomemobile.png";

import Project from "./project";

export class Projects extends Component {
  static propTypes = {};

  render() {
    const projects = [
      {
        key: 1,
        preview: {
          desktop: kendinonar,
          mobile: kendinonarmobile
        },
        name: "kendinonar",
        description: {
          __html:
            "<p>The project is generated by React, Redux, moment, react-router, firebase, redux-firebase, react-ckeditor-component, bootstrap. Authentication, database and hosting are provided by firebase. Authentication, database and hosting are provided by firebase.</p><p>Kendinonar is a Forum site aplication. It has an admin module to add/remove topics and subtopics, to change user privileges. Every forum module has add/edit topics and messages functionality to admins and other authenticated users. </p><p>This web site is a responsive web site.</p>"
        },
        link: "https://kendinonar.com",
        github: "https://github.com/erdogancihan/kendinonar.com"
      },
      {
        key: 2,
        preview: {
          desktop: myblog,
          mobile: myblogmobile
        },
        name: "MyBlogSite",
        description: {
          __html:
            "<p>The project is generated by React, Redux, react-helmet, moment, react-router, firebase, redux-firebase, react-ckeditor-component, sass. Authentication, database and hosting are provided by firebase.</p><p>This project is a multi language blog site. All labels and error mesages supports three languages.</p><p>For SEO every article has a route and by the help of React-Helmet each route's title and description is unique and contains article's title and description.</p><p>This is a responsive web site.</p><p>For more information please refer to github.</p>"
        },
        link: "https://myblog-48f35.firebaseapp.com/",
        github: "https://github.com/erdogancihan/react-blog-site"
      },
      {
        key: 3,
        preview: {
          desktop: sorular,
          mobile: sorularmobile
        },
        name: "Sorular",
        description: {
          __html:
          "<p>The project is generated by React, Redux, moment, react-router, firebase, redux-firebase, sass. Authentication, database and hosting are provided by firebase.</p><p>This project is a question-chalenge website. Authenticated user has 3 tryouts within an hour. User is asked randomly selected questions from database. User has 30 seconds to answer a question. User has three jokers for each try. 'extend time', 'eliminate two wrong answers' and 'by-pass the question' After each tier user is asked more dificult questions.</p><p>Application has a module to add, edit and view all questions.</p> <p>This is a responsive web site.</p><p>For more information please refer to github.</p>"
          
        },
        link: "https://sorular-a37b9.firebaseapp.com/",
        github: "https://github.com/erdogancihan/sorular"
      },
      {
        key: 4,
        preview: {
          desktop: floppyhome,
          mobile: floppyhomemobile
        },
        name: "FloppyHome",
        description: {
          __html:
            "<p>This is a single page responsive web site. </p><p>It is not interactive. </p>"
        },
        link: "https://floppyhome.com",
        github: "https://github.com/erdogancihan/floppyhome"
      }
    ];
    return (
      <section id="projects">
        <div className="container">
          <h1>PROJECTs</h1>
          {projects.map(project => {
            return <Project project={project} key={project.key} />;
          })}
        </div>
      </section>
    );
  }
}

export default Projects;
